# Change these first
owner: valicek1
repo: upptime

sites:
  - name: "[SERV] Uptime Kuma"
    url: https://kuma.sw3.cz

  - name: "[SW3] Flákač"
    url: https://flakac.sw3.cz
  - name: "[SW3] Hppro"
    url: https://hppro.sw3.cz
  - name: "[SW3] Ispconfig"
    url: https://config.sw3.cz
  - name: "[SW3] Kripl"
    url: https://kripl.sw3.cz/test.html
  - name: "[SW3] Lemra"
    url: https://lemra.sw3.cz
  - name: "[SW3] LemraDNS"
    url: https://lemradns.sw3.cz
  - name: "[SW3] Šmírák"
    url: https://smirak.sw3.cz
  - name: "[SW3] Trpaslík"
    url: trpaslik.sw3.cz
    port: $WINBOX_PORT
    check: "tcp-ping"
  - name: "[SW3] Zmetak"
    url: https://zmetek.sw3.cz

  - name: "[SW3] Nextcloud"
    url: https://cloud.sw3.cz
  - name: "[SW3] HASS"
    url: https://ha.sw3.cz
  - name: "[SW3] ha-ovalenta"
    url: https://ovalenta.sw3.cz

  - name: "[YC] Blb"
    check: "tcp-ping"
    url: blb.ycnet.cz
    port: 22

  - name: "[YC] Blekota"
    check: "tcp-ping"
    url: blekota.ycnet.cz
    port: 22

  - name: "[YC] Nemehlo"
    check: "tcp-ping"
    url: nemehlo.ycnet.cz
    port: 22

  - name: Test_W520
    url: bkp-w520.duckdns.org
    port: 8080
    ipv6: true

  - name: "[STORJ] kripl:storageBlb"
    check: "tcp-ping"
    url: kripl.sw3.cz
    port: 28969

  - name: "[STORJ] kripl:storage500"
    check: "tcp-ping"
    url: kripl.sw3.cz
    port: 28968

  - name: "[STORJ] kripl:storage800"
    check: "tcp-ping"
    url: kripl.sw3.cz
    port: 28967 

  - name: "[STORJ] zmetek:storagenode1"
    check: "tcp-ping"
    url: zmetek.sw3.cz
    port: 28967

  - name: "[STORJ] zmetek:storagenode2"
    check: "tcp-ping"
    url: zmetek.sw3.cz
    port: 28968

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** of sw3.cz / ycnet.cz"
  introMessage: HTTP/s uptime monitor
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
